### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by stevojhall** [Malorolam/LootBags#108] opened 2017-12-29 09:21 UTC
i started getting issues with textures not showing for the bags, the 3 machines still have textures, at first i thought it was the issue with advanced rocketry and libvulpes but have disabled them and clean reinstalled lootbags and i still get no textures.

minecraft version: 1.12.2
forge version: forge-1.12.2-14.23.1.2582-universal.jar
mod version: LootBags-1.12.2-2.5.3b.jar

**Comment by 4Magma** [comment] 2017-12-29 10:40
could you have installed 
disenchanter-[1.12]1.5.jar
i had a similar issue (bag textures wrong, blocks ok) with both until i disabled disenchanter.

**Comment by stevojhall** [comment] 2017-12-29 18:53
no, no disenchanter mod installed

**Comment by Malorolam** [comment] 2017-12-29 22:17
I can take a look and see if I can pin down why this is happening.  I'm not doing anything odd with rendering/registration though.

**Comment by Gunvaldfar** [comment] 2018-01-24 18:21
I have also missing textures - only the bags

**Comment by smbarbour** [comment] 2018-02-06 00:48
Just to contribute to the strangeness.  Maybe the same issue, maybe not...  On my own modpack, the common lootbag has the pink and black block texture, but even stranger... the manual for the Cobbleworks mod has the texture a common lootbag SHOULD have.

**Comment by Malorolam** [comment] 2018-02-06 03:24
A bit of an update on this.  With Cobbleworks I have a mod that always causes the issue the same way so I can properly test it and find the problem.  I'm hoping cobbleworks and the earlier issues with disenchanter and other mods are all the same problem.
Testing a bit and it appears related to how the models are registered in the renderer code, it's letting other items get put in with Lootbags so those models (and textures) are replacing the associated bags at that metadata, then the original items aren't actually getting registered correctly.  I think it's a bit of a communal error where I and a collection of other mod devs didn't add a method call we were supposed to.

**Comment by Cypress187** [comment] 2018-02-08 14:04
Is there a workaround for now? I have the same problem.

**Comment by Cypress187** [comment] 2018-02-10 14:36
There is a conflict with "better with mods", removed it and it fixes it, maybe you can work together to make both your mods more compatible with each-other.

**Comment by Malorolam** [comment] 2018-02-10 19:28
I'll test BWM and BOP before release, but if my hypothesis is correct then all the missing texture/mis-mapping issues should be fixed now, at least in regards to Lootbags.

**Comment by Malorolam** [comment] 2018-02-10 20:27
Fixed in 2.5.4

**Closed by Malorolam** 2018-02-10 20:27 UTC

**Comment by Impelon** [comment] 2018-03-21 14:14
@Malorolam Just to clarify: I'm the author of the Disenchanter Mod...
Sorry to bring this up again, but seeing that you have managed to fix this, I'm am wondering if you could link me directly to your solution or tell me where to read up on this. I'm really struggeling to solve this issue on my part...

**Comment by Malorolam** [comment] 2018-03-21 20:33
Sure.  I couldn't find any documentation or even forum posts with useful answers on this, so I kind of had to jank my way through this.  Digging through the code I found that the issue was being caused by different mods overwriting the textures in stitching, messing everything up.  The specific key to this that I found was that in IForgeRegistryEntry there's a field called public final IRegistryDelegate<T> delegate.  This as far as I can tell is what actually determines the mod sorting for the texture stitching (and probably other registry things) and since it's final, if both bits of information aren't there it just applies default values, which pools all the textures and causes them to overwrite each other.
This led me to try and figure out why the information wasn't being applied, since these fields are initialized when the item is.  I figured that it had something to do with where the rendering registration was being done, so I moved it around a bit.  What I found to work is register the item rendering directly after registering the item, which for me is in the RegistrationHandler event system they added in 1.11, my code for that is [here.](https://github.com/Malorolam/LootBags/blob/1efab039b6f8a3acaae54ab3d6952833956b5222/mal/lootbags/LootBags.java#L363).

**Comment by Impelon** [comment] 2018-03-21 20:42
Ok, thanks for the explanation and the link to the code.
I also noticed that Forge will try to register my model on completely different items/etc.. For example Buildcraft's Oil had this issue in the 7.99.12 build. I've changed my model registration a bit and noticed, that apparently Forge tried to register the model for BC Oil's Blockstate with my StateMapper. Whatever, strange behavior; this doesn't even seem that related to the other issue, since it doesn't have to do with the items, but still. 
Anyways, thanks again for the help, hopefully I can get this to work, too.

**Comment by 233Neon** [comment] 2022-08-29 15:31
I'm having the same issue with the newest version. It only happens for custom items in the config that use a custom mesh model (Cosmi-Rod, Infinity Gauntlet, etc). I'm not 100% on that though. 

**Here's what I put in config:**
```
"whitelisted items" {
    S:"Global Whitelist" <
	lucraftcore:infinity_gauntlet:1:1:1:16
        adminweapons:lightningstaff:1:1:1:16
        adminweapons:teleport_admin_sword:1:1:1:16
        adminweapons:admin_rocket_launcher:1:1:1:16
        adminweapons:glass_launcher:1:1:1:16
        adminweapons:fire_admin_sword:1:1:1:16
        adminweapons:air_admin_sword:1:1:1:16
        adminweapons:admin_gun:1:1:1:16
        infinityarmor:infinity_armor_head:1:1:1:16
        infinityarmor:infinity_armor_chest:1:1:1:16
        infinityarmor:infinity_armor_legs:1:1:1:16
        infinityarmor:infinity_armor_feet:1:1:1:16
        infinityarmor:greengem:1:1:1:16
        infinityarmor:purplegem:1:1:1:16
        infinityarmor:redgem:1:1:1:16
        infinityarmor:bluegem:1:1:1:16
        infinityarmor:orangegem:1:1:1:16
        infinityarmor:yellowgem:1:1:1:16
        infinityarmor:infinity_shield:1:1:1:16
        infinityarmor:netherite_armor_head:1:1:1:16
        infinityarmor:netherite_armor_chest:1:1:1:16
        infinityarmor:netherite_armor_legs:1:1:1:16
        infinityarmor:netherite_armor_feet:1:1:1:16
        infinityarmor:netherite_shield:1:1:1:16
        infinityarmor:netherite_sword:1:1:1:16
        infinityarmor:rainbowgems:1:1:1:16
        infinityarmor:infinity_trident:1:1:1:16
        infinity:power_stone:1:1:1:16
        infinity:mind_stone:1:1:1:16
        infinity:reality_stone:1:1:1:16
        infinity:soul_stone:1:1:1:16
        infinity:time_stone:1:1:1:16
        infinity:space_stone:1:1:1:16
        wakanda:infinity_gauntlet_chest:1:1:1:16
        wakanda:black_panther_infinity_suit:1:1:1:16
        dfheroes:infinity_gauntlet_chest:1:1:1:16
        lucraftcore:infinity_generator:1:1:1:16
		lucraftcore:injection:1:1:1:16:[luckythanos:randominjection]
		lucraftcore:injection:1:1:1:16:[heroesarrival:venom]
        avaritia:infinity_helmet:1:1:1:16
        avaritia:infinity_chestplate:1:1:1:16
        avaritia:infinity_pants:1:1:1:16
        avaritia:infinity_boots:1:1:1:16
        cosmosshield:infinity_gun:1:1:1:16
        cosmosshield:cosmos_shield:1:1:1:16
        avaritia:infinity_sword:1:1:1:16
        avaritia:infinity_pickaxe:1:1:1:16
        avaritia:infinity_bow:1:1:1:16
        avaritia:resource:1:1:1:16
        avaritia:block_resource:1:1:1:16
        avaritia:infinity_hoe:1:1:1:16
        avaritia:infinity_axe:1:1:1:16
        avaritia:infinity_shovel:1:1:1:16
        avaritia:skullfire_sword:1:1:1:16
        draconicadditions:chaotic_helm:1:1:1:16
        draconicadditions:chaotic_chest:1:1:1:16
        draconicadditions:chaotic_legs:1:1:1:16
        draconicadditions:chaotic_boots:1:1:1:16
        draconicadditions:chaotic_staff_of_power:1:1:1:16
        draconicevolution:draconic_helm:1:1:1:16
        draconicevolution:draconic_chest:1:1:1:16
        draconicevolution:draconic_legs:1:1:1:16
        draconicevolution:draconic_boots:1:1:1:16
        draconicevolution:creative_rf_source:1:1:1:16
        draconicevolution:energy_infuser:1:1:1:16
        draconicevolution:chaos_shard:1:1:1:16
        draconicevolution:draconic_reactor_core:1:1:1:16
        draconicevolution:draconic_block:1:1:1:16
        draconicadditions:potato_helm:1:1:1:16
        draconicadditions:potato_chest:1:1:1:16
        draconicadditions:potato_legs:1:1:1:16
        draconicadditions:potato_boots:1:1:1:16
        draconicevolution:draconic_staff_of_power:1:1:1:16
        draconicevolution:wyvern_helm:1:1:1:16
        draconicevolution:wyvern_chest:1:1:1:16
        draconicevolution:wyvern_legs:1:1:1:16
        draconicevolution:wyvern_boots:1:1:1:16
        draconicevolution:tool_upgrade:1:1:1:16
        draconicevolution:dislocator_bound:1:1:1:16
        heroesexpansion:mjolnir:1:1:1:16
        heroesexpansion:ultimate_mjolnir:1:1:1:16
        heroesexpansion:cape:1:1:1:16
        heroesexpansion:compound_bow:1:1:1:16
        heroesexpansion:quiver:1:1:1:16
        heroesexpansion:kryptonite_arrow:1:1:1:16
        heroesexpansion:vibranium_arrow:1:1:1:16
        heroesexpansion:portal_device:1:1:1:16
        heroesexpansion:captain_america_shield:1:1:1:16
        heroesexpansion:vibranium_shield:1:1:1:16
        heroesexpansion:wakandan_shield:1:1:1:16
        heroesexpansion:chitauri_gun:1:1:1:16
        heroesexpansion:web_shooter_2:1:1:1:16
        heroesexpansion:chitauri_energy_core:1:1:1:16
        heroesexpansion:kree_battle_axe:1:1:1:16
        heroesexpansion:kryptonite_block:1:1:1:16
        heroesexpansion:spider_man_helmet:1:1:1:16
        heroesexpansion:spider_man_chest:1:1:1:16
        heroesexpansion:spider_man_legs:1:1:1:16
        heroesexpansion:spider_man_boots:1:1:1:16
        heroesexpansion:spider_man_homemade_helmet:1:1:1:16
        heroesexpansion:spider_man_homemade_chest:1:1:1:16
        heroesexpansion:spider_man_homemade_legs:1:1:1:16
        heroesexpansion:spider_man_homemade_boots:1:1:1:16
        heroesexpansion:falcon_helmet:1:1:1:16
        heroesexpansion:falcon_chest:1:1:1:16
        heroesexpansion:falcon_legs:1:1:1:16
        heroesexpansion:falcon_boots:1:1:1:16
        heroesexpansion:daredevil_homemade_helmet:1:1:1:16
        heroesexpansion:daredevil_homemade_chest:1:1:1:16
        heroesexpansion:daredevil_homemade_legs:1:1:1:16
        heroesexpansion:daredevil_homemade_boots:1:1:1:16
        heroesexpansion:daredevil_helmet:1:1:1:16
        heroesexpansion:daredevil_chest:1:1:1:16
        heroesexpansion:daredevil_legs:1:1:1:16
        heroesexpansion:daredevil_boots:1:1:1:16
        heroesexpansion:captain_marvel_helmet:1:1:1:16
        heroesexpansion:captain_marvel_chest:1:1:1:16
        heroesexpansion:captain_marvel_legs:1:1:1:16
        heroesexpansion:captain_marvel_boots:1:1:1:16
        heroesexpansion:thor_iw_chest:1:1:1:16
        heroesexpansion:thor_iw_legs:1:1:1:16
        heroesexpansion:thor_iw_boots:1:1:1:16
        heroesexpansion:thor_chest:1:1:1:16
        heroesexpansion:thor_legs:1:1:1:16
        heroesexpansion:thor_boots:1:1:1:16
        heroesexpansion:green_arrow_chest:1:1:1:16
        heroesexpansion:green_arrow_legs:1:1:1:16
        heroesexpansion:green_arrow_boots:1:1:1:16
        opweaponsmod:potion_of_omnipotence:1:1:1:16
        opweaponsmod:rod_of_enragement:1:1:1:16
        pymtech:ant_man_helmet:1:1:1:16
        pymtech:ant_man_chest:1:1:1:16
        pymtech:ant_man_legs:1:1:1:16
        pymtech:ant_man_boots:1:1:1:16
        pymtech:shrink_disk:1:1:1:16
        pymtech:grow_disk:1:1:1:16
        icbmclassic:explosives:1:1:1:16
        mcum:t_skull:1:1:1:16
        mcum:d_blade_sword:1:1:1:16
        luckythanos:itemlp:1:1:1:16
        xreliquary:rod_of_lyssa:1:1:1:16
        xreliquary:glowing_bread:1:1:1:16
        xreliquary:ender_staff:1:1:1:16
        xreliquary:rending_gale:1:1:1:16
        xreliquary:witch_hat:1:1:1:16
        xreliquary:handgun:1:1:1:16
        galacticraftplanets:titanium_sword:1:1:1:16
        mowziesmobs:grant_suns_blessing:1:1:1:16
        mowziesmobs:wrought_axe:1:1:1:16
        nateexpandedmultiverse:phoelconspacesuit_helmet:1:1:1:16
        nateexpandedmultiverse:phoelconspacesuit_chest:1:1:1:16
        nateexpandedmultiverse:phoelconspacesuit_legs:1:1:1:16
        nateexpandedmultiverse:phoelconspacesuit_boots:1:1:1:16
        nateexpandedmultiverse:phoelcon_suit_tier3_helmet:1:1:1:16
        nateexpandedmultiverse:phoelcon_suit_tier3_chest:1:1:1:16
        nateexpandedmultiverse:phoelcon_suit_tier3_legs:1:1:1:16
        nateexpandedmultiverse:phoelcon_suit_tier3_boots:1:1:1:16
        star-tech:cosmi_rod:1:1:1:16
        heroesexpansion:tesseract:1:1:1:16
        avengerstech:scepter:1:1:1:16
        heroesarrival:iron_gauntlet:1:1:1:16
     >
}

```
