### ISSUE TITLE
Texture broken..

### ISSUE THREAD

**Issue by SilverHuskey** [Malorolam/LootBags#157] opened 2018-10-09 17:49 UTC
Lootbags texture breaks for me when i added a texturepack to my modpack. Is there any way i can manually readd the texture to the pack or something?
![image](https://user-images.githubusercontent.com/25567848/46687924-05871e00-cbf4-11e8-946e-9ff68ac90675.png)

Also this happens in creative

![image](https://user-images.githubusercontent.com/25567848/46687905-f7d19880-cbf3-11e8-9965-b991fa81bfcb.png)

**Comment by Malorolam** [comment] 2018-10-09 23:33
The textures should not be breaking unless the texture pack itself is trying to tweak them.  I need more information before I can find the problem, the texture pack and any other mods you're using.

**Comment by SilverHuskey** [comment] 2018-10-10 21:01
https://www.dropbox.com/s/8cjmq8m455eqj02/Essence%20Of%20Nature.zip?dl=0

^^ TexturePack

![image](https://user-images.githubusercontent.com/25567848/46765830-fed1d700-ccd7-11e8-9c8e-a4f1f45b98a4.png)

^^ Mod list

**Comment by Malorolam** [comment] 2018-10-11 00:07
Looking at the texture pack and mod list, I'd say the most likely culprit is Optifine or that Lootbags didn't download completely and it's missing the textures.

**Comment by SilverHuskey** [comment] 2018-10-25 03:44
Sorry for the late reply, Got busy with other stuff. So i cant find any issue with lootbags or Optifine

**Comment by SilverHuskey** [comment] 2018-10-25 16:08
> Looking at the texture pack and mod list, I'd say the most likely culprit is Optifine or that Lootbags didn't download completely and it's missing the textures.

Is there a way i could just get the textures from your mod and MANUALLY add them to the texturepack? if so how and where do the files belong?

**Comment by Malorolam** [comment] 2018-10-25 22:57
How resourcepacks work is that the textures are stitched together from all the enabled packs, they only replace textures that they have.  While you can open up the .jar file and pull the textures out into a resource pack, that won't fix the actual problem.

To confirm and check off, did you:
1. Update all mods to their latest versions and verify the issue still happens
2. Remove Optifine and verify if the issue still happens with the texture pack loaded
3. Completely delete Lootbags and redownload it from CurseForge or the Twitch launcher, then verify the issue is not resolved
4. Close the game, delete lootbags.cfg and Lootbags_BagConfig.cfg, run the game again and verify the issue is still there
5. Disable the texture pack and confirm the issue goes away

**Closed** 2019-05-11 16:47 UTC
