### ISSUE TITLE
Crash on pack load

### ISSUE THREAD

**Issue by Cazadorsniper** [Malorolam/LootBags#176] opened 2019-02-24 23:12 UTC
I tried update 2.5.8 and this happened: https://pastebin.com/QS9SMuRW

**Comment by Malorolam** [comment] 2019-02-24 23:26
Give me the two configs too, it looks like something wonky is happening with one of the lists.

**Comment by Cazadorsniper** [comment] 2019-02-25 00:51
lootbag.cfg-https://pastebin.com/tyC1Wz15
bagconfig-https://pastebin.com/YwT4iyzV

**Comment by Malorolam** [comment] 2019-02-25 01:33
I'm not seeing how it could break from just updating Lootbags. Did you update any other mods, and is this a full modpack or something you threw together?

**Comment by Cazadorsniper** [comment] 2019-02-25 02:45
Its Project Ozone 3 the mods I updated so far have been: 
# ExNihiloCreatio
# Land Craft
# Corail Tombstone
# Aroma1997sCore
# Botania
# Apple Core
# YABBA
# AutoRegLib
# Equivalent Integration
# Quark
# Lordcraft
# Fastworkbench
# Lostcities
# CyclopsCore
# Industrial Foregoing
# Abyssalcraft Integration
# Immersive Engineering
# Integration Foregoing
# Abyssalcraft
# CyclopsCore
# Everlasting Abilities
# B.A.S.E

**Comment by Malorolam** [comment] 2019-02-25 03:01
Probably should have guessed that. Most of those don't add loot, but to be sure, can you downgrade Lootbags and see if it still crashes? I didn't change the section of the code that's breaking so I'm hoping it's something odd from another mod that I can add better error handling for and not some major problem on my end.

**Comment by Cazadorsniper** [comment] 2019-02-25 03:05
I downgraded before and it didn't crash, i tested the update again and same crash

**Comment by Malorolam** [comment] 2019-02-25 03:25
Alright, I've narrowed it down to because of blacklisting the spectre coil, so if you un-blacklist it, everything should load again. No clue why it would break it now and not before, but I'll work on it and get a proper fix.

**Comment by Cazadorsniper** [comment] 2019-02-25 03:28
Okay, that is weird.

**Comment by Malorolam** [comment] 2019-02-26 00:26
It turns out the issue is caused because I moved the blacklisting and whitelisting code to preInit for some reason I've forgotten, which means that any modded item is likely not initialized yet. I'll have a fix out soon.

**Comment by Malorolam** [comment] 2019-02-27 02:02
Fixed in 2.5.8.5.

**Closed by Malorolam** 2019-02-27 02:02 UTC
